source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'UIImageView_AFNetworking-Blocks' do
  pod "UIImageView_AFNetworking-Blocks", :path => "../"
end

target 'Tests' do
  pod "UIImageView_AFNetworking-Blocks", :path => "../"
end
